apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../resources/

namespace: default

# namePrefix: fa-
# nameSuffix: -production

commonLabels:
  application: fleetman-production
  owner: subrahmanyam-r

# configMapGenerator:
# - name: production-configuration
#   behavior: create
#   files:
#   - application.properties
# - name: tracing-options
#   behavior: create
#   envs:
#   - debug.environment

images:
- name: subrahmanyamr/fleetman-webapp
  newName: subrahmanyamr/fleetman-webapp
  newTag: 1.0.0
- name: subrahmanyamr/fleetman-api-gateway
  newName: subrahmanyamr/fleetman-api-gateway
  newTag: 1.0.0
- name: subrahmanyamr/fleetman-position-simulator
  newName: subrahmanyamr/fleetman-position-simulator
  newTag: 1.0.0
- name: subrahmanyamr/fleetman-position-tracker
  newName: subrahmanyamr/fleetman-position-tracker
  newTag: 1.0.0
- name: subrahmanyamr/fleetman-queue
  newName: subrahmanyamr/fleetman-queue
  newTag: 1.0.0
- name: mongo
  newName: mongo
  newTag: 3.6.5-jessie